name: Android Environment Setup
inputs:
  install-vale:
    description: 'Install vale prose linter'
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: Free disk space
      uses: ./mobile-android-pipelines/actions/clean-runner-fast

    - name: Clean workspace
      uses: ./mobile-android-pipelines/actions/clean-workspace

    - name: Configure git User
      shell: bash
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Setup common prerequisites
      uses: ./mobile-android-pipelines/actions/common-prerequisites
      with:
        install-vale: ${{ inputs.install-vale }}
