#!/usr/bin/env bash
# Exit immediately if a simple command exits with a non-zero status
# see also: the 'set' command within the 'Shell Builtin Commands' section of `man bash`
set -o errexit

source "$(git rev-parse --show-toplevel)/scripts/env"

echo "Git root: ${GIT_ROOT}"

if command -v vale; then
  echo "Vale is already installed. Syncing..."
else
  echo "Vale is unavailable! Installing..."
  "${GIT_ROOT}"/scripts/lint/vale/install
fi

vale sync
vale --no-wrap --glob='!**/mobile-android-pipelines/**/*.*' --config="${GIT_ROOT}/.vale.ini" "${GIT_ROOT}/"
